# config/config.yaml
database:
  dialect: postgresql
  user: postgres
  password: admin
  host: localhost
  port: 5432
  database: postgres


load_process:
  schema: loads
  table_name: etl_load_log
  sequence_name: etl_process_seq
  
encryption:
  key_path: "config/secret.key"
  columns_to_encrypt:
    - customer_id
    - product_id



files_to_tables_tmp:
  - file_path: data/sales_transactions.csv
    schema: etl_assesment_data
    table: sales_tmp

files_to_tables_inc:
  - tmp_schema: etl_assesment_data
    tmp_table: sales_tmp
    target_schema: etl_assesment_data
    target_table: sales
    unique_keys: ["transaction_id", "customer_id", "product_id", "quantity", "timestamp"]


mock_data:
  - file_path: data/sales_transactions.csv
    num_rows: 10000
    columns:
      transaction_id: random_unique_int_1_9999999
      customer_id: random_int_1000_1100
      product_id: random_int_200_250
      quantity: random_int_1_10
      timestamp: datetime_now_minus_random_minutes_0_100000


  - file_path: data/sales_transactions_v1.csv
    num_rows: 10000
    columns:
      transaction_id: int_sequence
      customer_id: random_int_1000_1100
      product_id: random_int_200_250
      quantity: random_int_1_10
      timestamp: datetime_now_minus_random_minutes_0_100000

